version: "2"

services:
  
  rng:
    build: rng
    ports:
    - "8001:80"
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201

  hasher:
    build: hasher
    ports:
    - "8003:80"
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201

  worker:
    build: worker
    ports:
    - "8002:80"
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
